### ISSUE TITLE
Make v1.6.4 available on Ansible Galaxy

### ISSUE THREAD

**Issue by sujaymansingh** [Stouts/Stouts.sentry#11]
The latest version on Ansible Galaxy is still v1.6.1

Could we please get v1.6.4? In particular it is for the change in @1e548335515ea608cc0df50ccca640547015c37e#diff-36ca9d0f2cd11e460433409381b7f923

Without it, I can't use any sentry more recent than 7.4.3 (and I need 7.5 so that I can set up API keys in the Organisation section!)

**Comment by klen** [comment]
Fixed, thank you for the feedback.
